### ISSUE TITLE
Ether lipid "O-" not recognized

### ISSUE THREAD

**Issue by dernesa** [lifs-tools/goslin#12]
**Describe the bug**
Ether lipids are misclassified as Di-acyl-species

**To Reproduce**
1. Go to [Goslin webapplication](https://apps.lifs.isas.de/goslin) v. 1.1.4
2. Enter "PC O-18:1_18:1"
3. click validate
4. See result as screen shot: **not working** . sn-1 ether connection is not recognized but classified as "Ester". Nevertheless, the lipid is named as "PC O-18:1-18:1"

**Expected behavior**
The same works when using "PC P-18:1/18:1". 
See result as screen shot: **working**. 
Else: If the lipid name is not correct, there should be an error. But the O- is transferred without error. 

**Screenshots**

not working: 
![not_working](https://user-images.githubusercontent.com/24799198/140834916-453ab7a3-a194-4897-8f21-83a70c2f7581.jpg)

working:

![working](https://user-images.githubusercontent.com/24799198/140835053-c5e2c0e7-65a7-4660-9bd3-9674b17d46e4.jpg)

**Additional context**
Thank you for your work. We plan to use Goslin starting with version 2.0.

**Comment by nilshoffmann** [comment]
This is an issue in jGoslin, specifically in the GoslinParserHandler. Tests that show that the bug is fixed are here: https://github.com/lifs-tools/jg/blob/main/parsers/src/test/java/org/lifstools/jgoslin/parser/GoslinParserTest.java#L115 and https://github.com/lifs-tools/jg/blob/main/parsers/src/test/java/org/lifstools/jgoslin/parser/GoslinParserTest.java#L124
