### ISSUE TITLE
Add ACer to Goslin grammars

### ISSUE THREAD

**Issue by nilshoffmann** [lifs-tools/goslin#38]
**Is your feature request related to a problem? Please describe.**
ACer (Acyl Ceramides) are currently not supported in the Goslin Grammars.

**Describe the solution you'd like**
ACers should be parseable and mapped similarly to other Ceramides.

ACers are currently not available in LIPID MAPS apparently.
SwissLipids has some examples: https://www.swisslipids.org/#/search/Acylceramide

**Comment by dominik-kopczynski** [comment]
Goslin supports ACers already within the current shorthand nomenclature. Try:

ACer(FA 22:6) 18:1;O2/16:0
ACer(FA) 66:1;O3

If it is not working, please drop me a line. This annotation is differing to that suggestion in the shorthand publication (Liebisch, 2020) since we decided with the shorthand group to update it.

Cheers,
Dominik
